n=input('Digite algo: ')
print('É um número? ', n.isnumeric())
print('É alfabético? ', n.isalpha())
print('É alfanumérico? ', n.isalnum())
print('Tem apenas espaços? ',n.isspace())
print('Está todo em maiúsculo?', n.isupper())
print('Está todo em minisculas? ',n.islower())
