n = str(input('Digite seu nome completo: ')).strip()
print('Seu nome em maiúsculas é: {} '.format(n.upper()))
print('Seu nome em minúsculas é: {}'.format(n.lower()))
print('Seu nome sem espaços possui {} letras.'.format(len(n) - n.count(' ')))
print('Seu primeiro nome possui {} letras. '.format(n.find(' ')))
separa = n.split()
print('Seu primeiro nome é {} e possui {} letras'.format(separa[0],len(separa[0])))
